// Generates one message barrel per namespace from i18n-namespaces.json.
//
// Why this exists: `$lib/paraglide/messages.js` re-exports every message, and a barrel that every
// route imports is a tree-shaking pinch point — the bundler hoists the union of all app-wide-used
// messages into one shared chunk that every page then downloads (paraglide-js#668). Importing each
// message module individually fixes it but means hand-maintaining hundreds of import lines with no
// editor auto-import (paraglide-js#345), and native namespace support is unimplemented
// (paraglide-js#531). So we generate the narrow barrels instead.
//
// A namespace barrel is imported by exactly one route subtree, so the bundler has no reason to hoist
// it, and the page gets only the copy it renders.
//
//   node scripts/gen-message-namespaces.ts           # write barrels
//   node scripts/gen-message-namespaces.ts --check   # fail if barrels are stale

import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const WEB_ROOT = resolve(import.meta.dirname, "..");
const CONFIG_PATH = join(WEB_ROOT, "i18n-namespaces.json");
const CATALOGS = ["messages/en.json", "messages/reader/en.json"];
const OUT_DIR = join(WEB_ROOT, "src/lib/i18n/m");
const MESSAGE_MODULE_BASE = "$lib/paraglide/messages";

interface NamespaceConfig {
  id: string;
  description: string;
  prefixes?: string[];
  keys?: string[];
}

interface Config {
  note: string;
  namespaces: NamespaceConfig[];
}

const check = process.argv.includes("--check");
const config = JSON.parse(readFileSync(CONFIG_PATH, "utf8")) as Config;

const catalogKeys = CATALOGS.flatMap((catalog) => {
  const parsed = JSON.parse(readFileSync(join(WEB_ROOT, catalog), "utf8")) as Record<
    string,
    unknown
  >;
  return Object.keys(parsed).filter((key) => key !== "$schema");
});

const duplicates = catalogKeys.filter((key, index) => catalogKeys.indexOf(key) !== index);
if (duplicates.length > 0) {
  throw new Error(`[i18n-ns] duplicate keys across catalogs: ${duplicates.join(", ")}`);
}

// Exact keys win over prefixes so a lazy sub-panel can be carved out of a broad prefix.
const explicit = new Map<string, string>();
for (const namespace of config.namespaces) {
  for (const key of namespace.keys ?? []) {
    const owner = explicit.get(key);
    if (owner) {
      throw new Error(`[i18n-ns] key "${key}" claimed by both "${owner}" and "${namespace.id}"`);
    }
    explicit.set(key, namespace.id);
  }
}

const unknownExplicit = [...explicit.keys()].filter((key) => !catalogKeys.includes(key));
if (unknownExplicit.length > 0) {
  throw new Error(
    `[i18n-ns] i18n-namespaces.json lists keys that no catalog defines: ${unknownExplicit.join(", ")}`,
  );
}

/** Longest prefix wins, so `reader_surface` can be claimed away from `reader`. */
function prefixOwner(key: string): string | undefined {
  let best: { id: string; length: number } | undefined;
  for (const namespace of config.namespaces) {
    for (const prefix of namespace.prefixes ?? []) {
      if (key === prefix || key.startsWith(`${prefix}_`)) {
        if (!best || prefix.length > best.length)
          best = { id: namespace.id, length: prefix.length };
      }
    }
  }
  return best?.id;
}

const membership = new Map<string, string[]>(config.namespaces.map((ns) => [ns.id, []]));
const unassigned: string[] = [];
for (const key of catalogKeys) {
  const owner = explicit.get(key) ?? prefixOwner(key);
  if (!owner) {
    unassigned.push(key);
    continue;
  }
  (membership.get(owner) as string[]).push(key);
}

if (unassigned.length > 0) {
  throw new Error(
    `[i18n-ns] ${unassigned.length} key(s) belong to no namespace: ${unassigned.join(", ")}\n` +
      `Add a prefix rule or an explicit key to i18n-namespaces.json. A key with no namespace has ` +
      `no defined download boundary.`,
  );
}

const empty = [...membership].filter(([, keys]) => keys.length === 0).map(([id]) => id);
if (empty.length > 0) {
  throw new Error(`[i18n-ns] namespace(s) claim no keys: ${empty.join(", ")}`);
}

function render(namespace: NamespaceConfig, keys: string[]): string {
  const exports = [...keys]
    .sort()
    .map((key) => `export { ${key} } from "${MESSAGE_MODULE_BASE}/${key}.js";`)
    .join("\n");

  return [
    `// AUTO-GENERATED by scripts/gen-message-namespaces.ts — do not edit.`,
    `//`,
    `// ${namespace.description}`,
    `//`,
    `// ${keys.length} message${keys.length === 1 ? "" : "s"}. Import this barrel, never`,
    `// $lib/paraglide/messages.js — see docs/i18n-bundle-plan.md.`,
    ``,
    exports,
    ``,
  ].join("\n");
}

const expected = new Map<string, string>();
for (const namespace of config.namespaces) {
  expected.set(`${namespace.id}.ts`, render(namespace, membership.get(namespace.id) as string[]));
}

const existing = new Map<string, string>();
try {
  for (const file of readdirSync(OUT_DIR)) {
    existing.set(file, readFileSync(join(OUT_DIR, file), "utf8"));
  }
} catch {
  // First run: nothing generated yet.
}

const stale = [...expected]
  .filter(([file, content]) => existing.get(file) !== content)
  .map(([f]) => f);
const orphaned = [...existing.keys()].filter((file) => !expected.has(file));

if (check) {
  if (stale.length > 0 || orphaned.length > 0) {
    console.error(
      `[i18n-ns] generated barrels are stale. Run: pnpm i18n:namespaces\n` +
        (stale.length > 0 ? `  outdated: ${stale.join(", ")}\n` : "") +
        (orphaned.length > 0 ? `  orphaned: ${orphaned.join(", ")}\n` : ""),
    );
    process.exit(1);
  }
  console.log(`[i18n-ns] ${expected.size} namespaces up to date (${catalogKeys.length} messages)`);
} else {
  mkdirSync(OUT_DIR, { recursive: true });
  for (const file of orphaned) rmSync(join(OUT_DIR, file));
  for (const [file, content] of expected) writeFileSync(join(OUT_DIR, file), content);
  const summary = config.namespaces
    .map((ns) => `${ns.id}=${(membership.get(ns.id) as string[]).length}`)
    .join(" ");
  console.log(
    `[i18n-ns] ${expected.size} namespaces written (${catalogKeys.length} messages): ${summary}`,
  );
}
