// AUTO-GENERATED by scripts/gen-message-namespaces.ts — do not edit.
//
// About page.
//
// 14 messages. Import this barrel, never
// #lib/paraglide/messages.js — see docs/quran-system.md (Part 2, Message chunking).

export { about_credit_built_by } from "#lib/paraglide/messages/about_credit_built_by.js";
export { about_credit_project_by } from "#lib/paraglide/messages/about_credit_project_by.js";
export { about_cta } from "#lib/paraglide/messages/about_cta.js";
export { about_feature_scripts } from "#lib/paraglide/messages/about_feature_scripts.js";
export { about_feature_tools } from "#lib/paraglide/messages/about_feature_tools.js";
export { about_feature_translations } from "#lib/paraglide/messages/about_feature_translations.js";
export { about_heading } from "#lib/paraglide/messages/about_heading.js";
export { about_intro } from "#lib/paraglide/messages/about_intro.js";
export { about_seo_description } from "#lib/paraglide/messages/about_seo_description.js";
export { about_seo_title } from "#lib/paraglide/messages/about_seo_title.js";
export { about_sources_arabic } from "#lib/paraglide/messages/about_sources_arabic.js";
export { about_sources_heading } from "#lib/paraglide/messages/about_sources_heading.js";
export { about_sources_note } from "#lib/paraglide/messages/about_sources_note.js";
export { about_sources_translations } from "#lib/paraglide/messages/about_sources_translations.js";
