// AUTO-GENERATED by scripts/gen-message-namespaces.ts — do not edit.
//
// About page.
//
// 18 messages. Import this barrel, never
// $lib/paraglide/messages.js — see docs/quran-system.md (Part 2, Message chunking).

export { about_body_approach } from "$lib/paraglide/messages/about_body_approach.js";
export { about_body_sources } from "$lib/paraglide/messages/about_body_sources.js";
export { about_body_today } from "$lib/paraglide/messages/about_body_today.js";
export { about_credit_built_by } from "$lib/paraglide/messages/about_credit_built_by.js";
export { about_credit_note } from "$lib/paraglide/messages/about_credit_note.js";
export { about_credit_project_by } from "$lib/paraglide/messages/about_credit_project_by.js";
export { about_cta } from "$lib/paraglide/messages/about_cta.js";
export { about_eyebrow } from "$lib/paraglide/messages/about_eyebrow.js";
export { about_heading } from "$lib/paraglide/messages/about_heading.js";
export { about_intro } from "$lib/paraglide/messages/about_intro.js";
export { about_seo_description } from "$lib/paraglide/messages/about_seo_description.js";
export { about_seo_title } from "$lib/paraglide/messages/about_seo_title.js";
export { about_stat_free_label } from "$lib/paraglide/messages/about_stat_free_label.js";
export { about_stat_free_value } from "$lib/paraglide/messages/about_stat_free_value.js";
export { about_stat_growing_label } from "$lib/paraglide/messages/about_stat_growing_label.js";
export { about_stat_growing_value } from "$lib/paraglide/messages/about_stat_growing_value.js";
export { about_stat_script_label } from "$lib/paraglide/messages/about_stat_script_label.js";
export { about_stat_script_value } from "$lib/paraglide/messages/about_stat_script_value.js";
