// AUTO-GENERATED by scripts/gen-message-namespaces.ts — do not edit.
//
// Marketing appearance panel. Lazy: only downloaded once the panel is opened.
//
// 34 messages. Import this barrel, never
// $lib/paraglide/messages.js — see docs/i18n-bundle-plan.md.

export { accent_azure_label } from "$lib/paraglide/messages/accent_azure_label.js";
export { accent_emerald_label } from "$lib/paraglide/messages/accent_emerald_label.js";
export { accent_gold_label } from "$lib/paraglide/messages/accent_gold_label.js";
export { accent_plum_label } from "$lib/paraglide/messages/accent_plum_label.js";
export { surface_contrast_label } from "$lib/paraglide/messages/surface_contrast_label.js";
export { surface_contrast_note } from "$lib/paraglide/messages/surface_contrast_note.js";
export { surface_ink_label } from "$lib/paraglide/messages/surface_ink_label.js";
export { surface_ink_note } from "$lib/paraglide/messages/surface_ink_note.js";
export { surface_mocha_label } from "$lib/paraglide/messages/surface_mocha_label.js";
export { surface_mocha_note } from "$lib/paraglide/messages/surface_mocha_note.js";
export { surface_paper_label } from "$lib/paraglide/messages/surface_paper_label.js";
export { surface_paper_note } from "$lib/paraglide/messages/surface_paper_note.js";
export { surface_slate_label } from "$lib/paraglide/messages/surface_slate_label.js";
export { surface_slate_note } from "$lib/paraglide/messages/surface_slate_note.js";
export { tweaks_accent } from "$lib/paraglide/messages/tweaks_accent.js";
export { tweaks_analytics } from "$lib/paraglide/messages/tweaks_analytics.js";
export { tweaks_background } from "$lib/paraglide/messages/tweaks_background.js";
export { tweaks_clear } from "$lib/paraglide/messages/tweaks_clear.js";
export { tweaks_close_panel } from "$lib/paraglide/messages/tweaks_close_panel.js";
export { tweaks_copied } from "$lib/paraglide/messages/tweaks_copied.js";
export { tweaks_copy_css } from "$lib/paraglide/messages/tweaks_copy_css.js";
export { tweaks_custom_colours } from "$lib/paraglide/messages/tweaks_custom_colours.js";
export { tweaks_data_privacy } from "$lib/paraglide/messages/tweaks_data_privacy.js";
export { tweaks_derived_colours } from "$lib/paraglide/messages/tweaks_derived_colours.js";
export { tweaks_mode } from "$lib/paraglide/messages/tweaks_mode.js";
export { tweaks_off } from "$lib/paraglide/messages/tweaks_off.js";
export { tweaks_on } from "$lib/paraglide/messages/tweaks_on.js";
export { tweaks_performance } from "$lib/paraglide/messages/tweaks_performance.js";
export { tweaks_performance_reload } from "$lib/paraglide/messages/tweaks_performance_reload.js";
export { tweaks_pop } from "$lib/paraglide/messages/tweaks_pop.js";
export { tweaks_reset } from "$lib/paraglide/messages/tweaks_reset.js";
export { tweaks_settings } from "$lib/paraglide/messages/tweaks_settings.js";
export { tweaks_surface } from "$lib/paraglide/messages/tweaks_surface.js";
export { tweaks_theme } from "$lib/paraglide/messages/tweaks_theme.js";
