// AUTO-GENERATED by scripts/gen-message-namespaces.ts — do not edit.
//
// Auth modal + /login /register routes. Lazy: ships only inside the lazy auth chunk + auth routes.
//
// 34 messages. Import this barrel, never
// $lib/paraglide/messages.js — see docs/i18n-bundle-plan.md.

export { auth_close } from "$lib/paraglide/messages/auth_close.js";
export { auth_continue } from "$lib/paraglide/messages/auth_continue.js";
export { auth_continue_with_passkey } from "$lib/paraglide/messages/auth_continue_with_passkey.js";
export { auth_continue_with_provider } from "$lib/paraglide/messages/auth_continue_with_provider.js";
export { auth_create_account } from "$lib/paraglide/messages/auth_create_account.js";
export { auth_create_one_link } from "$lib/paraglide/messages/auth_create_one_link.js";
export { auth_dialog_description } from "$lib/paraglide/messages/auth_dialog_description.js";
export { auth_dialog_title } from "$lib/paraglide/messages/auth_dialog_title.js";
export { auth_display_name_placeholder } from "$lib/paraglide/messages/auth_display_name_placeholder.js";
export { auth_email_placeholder } from "$lib/paraglide/messages/auth_email_placeholder.js";
export { auth_field_authentication_code } from "$lib/paraglide/messages/auth_field_authentication_code.js";
export { auth_field_confirm_password } from "$lib/paraglide/messages/auth_field_confirm_password.js";
export { auth_field_display_name } from "$lib/paraglide/messages/auth_field_display_name.js";
export { auth_field_email } from "$lib/paraglide/messages/auth_field_email.js";
export { auth_field_password } from "$lib/paraglide/messages/auth_field_password.js";
export { auth_forgot_password_prompt } from "$lib/paraglide/messages/auth_forgot_password_prompt.js";
export { auth_have_account_prompt } from "$lib/paraglide/messages/auth_have_account_prompt.js";
export { auth_hide_password_aria } from "$lib/paraglide/messages/auth_hide_password_aria.js";
export { auth_more_sign_in_options_aria } from "$lib/paraglide/messages/auth_more_sign_in_options_aria.js";
export { auth_no_account_prompt } from "$lib/paraglide/messages/auth_no_account_prompt.js";
export { auth_oauth_error } from "$lib/paraglide/messages/auth_oauth_error.js";
export { auth_or_continue_with } from "$lib/paraglide/messages/auth_or_continue_with.js";
export { auth_password_min_placeholder } from "$lib/paraglide/messages/auth_password_min_placeholder.js";
export { auth_password_placeholder } from "$lib/paraglide/messages/auth_password_placeholder.js";
export { auth_please_wait } from "$lib/paraglide/messages/auth_please_wait.js";
export { auth_register_heading } from "$lib/paraglide/messages/auth_register_heading.js";
export { auth_register_subheading } from "$lib/paraglide/messages/auth_register_subheading.js";
export { auth_reset_password_link } from "$lib/paraglide/messages/auth_reset_password_link.js";
export { auth_show_password_aria } from "$lib/paraglide/messages/auth_show_password_aria.js";
export { auth_sign_in } from "$lib/paraglide/messages/auth_sign_in.js";
export { auth_sign_in_subheading } from "$lib/paraglide/messages/auth_sign_in_subheading.js";
export { auth_totp_heading } from "$lib/paraglide/messages/auth_totp_heading.js";
export { auth_totp_subheading } from "$lib/paraglide/messages/auth_totp_subheading.js";
export { auth_use_different_account } from "$lib/paraglide/messages/auth_use_different_account.js";
