// AUTO-GENERATED by scripts/gen-message-namespaces.ts — do not edit.
//
// Parameterized control labels shared by the marketing and reader appearance panels.
//
// 6 messages. Import this barrel, never
// $lib/paraglide/messages.js — see docs/quran-system.md (Part 2, Message chunking).

export { tweaks_accent_option } from "$lib/paraglide/messages/tweaks_accent_option.js";
export { tweaks_colour_input } from "$lib/paraglide/messages/tweaks_colour_input.js";
export { tweaks_colour_label } from "$lib/paraglide/messages/tweaks_colour_label.js";
export { tweaks_preset } from "$lib/paraglide/messages/tweaks_preset.js";
export { tweaks_reset_to_preset } from "$lib/paraglide/messages/tweaks_reset_to_preset.js";
export { tweaks_toggle_status } from "$lib/paraglide/messages/tweaks_toggle_status.js";
