// AUTO-GENERATED by scripts/gen-message-namespaces.ts — do not edit.
//
// FAQ page, including its FAQPage structured data.
//
// 20 messages. Import this barrel, never
// $lib/paraglide/messages.js — see docs/quran-system.md (Part 2, Message chunking).

export { faq_account_answer } from "$lib/paraglide/messages/faq_account_answer.js";
export { faq_account_question } from "$lib/paraglide/messages/faq_account_question.js";
export { faq_backup_answer } from "$lib/paraglide/messages/faq_backup_answer.js";
export { faq_backup_question } from "$lib/paraglide/messages/faq_backup_question.js";
export { faq_eyebrow } from "$lib/paraglide/messages/faq_eyebrow.js";
export { faq_free_answer } from "$lib/paraglide/messages/faq_free_answer.js";
export { faq_free_question } from "$lib/paraglide/messages/faq_free_question.js";
export { faq_heading } from "$lib/paraglide/messages/faq_heading.js";
export { faq_missing_link } from "$lib/paraglide/messages/faq_missing_link.js";
export { faq_missing_prompt } from "$lib/paraglide/messages/faq_missing_prompt.js";
export { faq_next_answer } from "$lib/paraglide/messages/faq_next_answer.js";
export { faq_next_question } from "$lib/paraglide/messages/faq_next_question.js";
export { faq_offline_answer } from "$lib/paraglide/messages/faq_offline_answer.js";
export { faq_offline_question } from "$lib/paraglide/messages/faq_offline_question.js";
export { faq_script_answer } from "$lib/paraglide/messages/faq_script_answer.js";
export { faq_script_question } from "$lib/paraglide/messages/faq_script_question.js";
export { faq_seo_description } from "$lib/paraglide/messages/faq_seo_description.js";
export { faq_seo_title } from "$lib/paraglide/messages/faq_seo_title.js";
export { faq_translations_answer } from "$lib/paraglide/messages/faq_translations_answer.js";
export { faq_translations_question } from "$lib/paraglide/messages/faq_translations_question.js";
