// AUTO-GENERATED by scripts/gen-message-namespaces.ts — do not edit.
//
// Marketing home page, including its SEO metadata.
//
// 31 messages. Import this barrel, never
// $lib/paraglide/messages.js — see docs/quran-system.md (Part 2, Message chunking).

export { landing_badge } from "$lib/paraglide/messages/landing_badge.js";
export { landing_coming } from "$lib/paraglide/messages/landing_coming.js";
export { landing_hero_intro } from "$lib/paraglide/messages/landing_hero_intro.js";
export { landing_hero_title } from "$lib/paraglide/messages/landing_hero_title.js";
export { landing_primary_cta } from "$lib/paraglide/messages/landing_primary_cta.js";
export { landing_roadmap_audio_body } from "$lib/paraglide/messages/landing_roadmap_audio_body.js";
export { landing_roadmap_audio_title } from "$lib/paraglide/messages/landing_roadmap_audio_title.js";
export { landing_roadmap_content_body } from "$lib/paraglide/messages/landing_roadmap_content_body.js";
export { landing_roadmap_content_title } from "$lib/paraglide/messages/landing_roadmap_content_title.js";
export { landing_roadmap_eyebrow } from "$lib/paraglide/messages/landing_roadmap_eyebrow.js";
export { landing_roadmap_intro } from "$lib/paraglide/messages/landing_roadmap_intro.js";
export { landing_roadmap_native_body } from "$lib/paraglide/messages/landing_roadmap_native_body.js";
export { landing_roadmap_native_title } from "$lib/paraglide/messages/landing_roadmap_native_title.js";
export { landing_roadmap_sync_body } from "$lib/paraglide/messages/landing_roadmap_sync_body.js";
export { landing_roadmap_sync_title } from "$lib/paraglide/messages/landing_roadmap_sync_title.js";
export { landing_roadmap_title } from "$lib/paraglide/messages/landing_roadmap_title.js";
export { landing_secondary_cta } from "$lib/paraglide/messages/landing_secondary_cta.js";
export { landing_today_eyebrow } from "$lib/paraglide/messages/landing_today_eyebrow.js";
export { landing_today_intro } from "$lib/paraglide/messages/landing_today_intro.js";
export { landing_today_title } from "$lib/paraglide/messages/landing_today_title.js";
export { landing_value_authentic_body } from "$lib/paraglide/messages/landing_value_authentic_body.js";
export { landing_value_authentic_title } from "$lib/paraglide/messages/landing_value_authentic_title.js";
export { landing_value_free_body } from "$lib/paraglide/messages/landing_value_free_body.js";
export { landing_value_free_title } from "$lib/paraglide/messages/landing_value_free_title.js";
export { landing_value_instant_body } from "$lib/paraglide/messages/landing_value_instant_body.js";
export { landing_value_instant_title } from "$lib/paraglide/messages/landing_value_instant_title.js";
export { landing_value_size_body } from "$lib/paraglide/messages/landing_value_size_body.js";
export { landing_value_size_title } from "$lib/paraglide/messages/landing_value_size_title.js";
export { seo_home_description } from "$lib/paraglide/messages/seo_home_description.js";
export { seo_home_image_alt } from "$lib/paraglide/messages/seo_home_image_alt.js";
export { seo_home_title } from "$lib/paraglide/messages/seo_home_title.js";
