// AUTO-GENERATED by scripts/gen-message-namespaces.ts — do not edit.
//
// Legal chrome shared by the privacy and terms pages.
//
// 4 messages. Import this barrel, never
// $lib/paraglide/messages.js — see docs/quran-system.md (Part 2, Message chunking).

export { legal_eyebrow } from "$lib/paraglide/messages/legal_eyebrow.js";
export { legal_placeholder_note } from "$lib/paraglide/messages/legal_placeholder_note.js";
export { legal_updated } from "$lib/paraglide/messages/legal_updated.js";
export { legal_updated_date } from "$lib/paraglide/messages/legal_updated_date.js";
