// AUTO-GENERATED by scripts/gen-message-namespaces.ts — do not edit.
//
// Privacy policy body.
//
// 22 messages. Import this barrel, never
// $lib/paraglide/messages.js — see docs/quran-system.md (Part 2, Message chunking).

export { legal_privacy_accounts_body } from "$lib/paraglide/messages/legal_privacy_accounts_body.js";
export { legal_privacy_accounts_heading } from "$lib/paraglide/messages/legal_privacy_accounts_heading.js";
export { legal_privacy_changes_body } from "$lib/paraglide/messages/legal_privacy_changes_body.js";
export { legal_privacy_changes_heading } from "$lib/paraglide/messages/legal_privacy_changes_heading.js";
export { legal_privacy_children_body } from "$lib/paraglide/messages/legal_privacy_children_body.js";
export { legal_privacy_children_heading } from "$lib/paraglide/messages/legal_privacy_children_heading.js";
export { legal_privacy_choices_body } from "$lib/paraglide/messages/legal_privacy_choices_body.js";
export { legal_privacy_choices_heading } from "$lib/paraglide/messages/legal_privacy_choices_heading.js";
export { legal_privacy_collect_body } from "$lib/paraglide/messages/legal_privacy_collect_body.js";
export { legal_privacy_collect_heading } from "$lib/paraglide/messages/legal_privacy_collect_heading.js";
export { legal_privacy_device_body } from "$lib/paraglide/messages/legal_privacy_device_body.js";
export { legal_privacy_device_heading } from "$lib/paraglide/messages/legal_privacy_device_heading.js";
export { legal_privacy_heading } from "$lib/paraglide/messages/legal_privacy_heading.js";
export { legal_privacy_hosting_body } from "$lib/paraglide/messages/legal_privacy_hosting_body.js";
export { legal_privacy_hosting_heading } from "$lib/paraglide/messages/legal_privacy_hosting_heading.js";
export { legal_privacy_notifications_body } from "$lib/paraglide/messages/legal_privacy_notifications_body.js";
export { legal_privacy_notifications_heading } from "$lib/paraglide/messages/legal_privacy_notifications_heading.js";
export { legal_privacy_questions_link } from "$lib/paraglide/messages/legal_privacy_questions_link.js";
export { legal_privacy_questions_prompt } from "$lib/paraglide/messages/legal_privacy_questions_prompt.js";
export { legal_privacy_seo_description } from "$lib/paraglide/messages/legal_privacy_seo_description.js";
export { legal_privacy_seo_title } from "$lib/paraglide/messages/legal_privacy_seo_title.js";
export { legal_privacy_summary } from "$lib/paraglide/messages/legal_privacy_summary.js";
