// AUTO-GENERATED by scripts/gen-message-namespaces.ts — do not edit.
//
// Theme mode names. Shared by chrome (nav toggle) and both appearance panels.
//
// 3 messages. Import this barrel, never
// $lib/paraglide/messages.js — see docs/quran-system.md (Part 2, Message chunking).

export { theme_dark } from "$lib/paraglide/messages/theme_dark.js";
export { theme_light } from "$lib/paraglide/messages/theme_light.js";
export { theme_system } from "$lib/paraglide/messages/theme_system.js";
