// GENERATED from IANA tzdata zone.tab, plus the legacy spelling ICU-based browsers report for each
// zone (Chrome: Asia/Calcutta for Asia/Kolkata). Only countries listed in REGION_LANGUAGES are kept.
// Regenerate if REGION_LANGUAGES gains a country; timezone↔country assignments change very rarely.

/** Country → its IANA timezone ids, space-separated (inverted on first lookup). */
export const COUNTRY_TIMEZONES: Readonly<Record<string, string>> = Object.freeze({
  AE: "Asia/Dubai",
  AF: "Asia/Kabul",
  AL: "Europe/Tirane",
  AR: "America/Argentina/Buenos_Aires America/Argentina/Catamarca America/Argentina/Cordoba America/Argentina/Jujuy America/Argentina/La_Rioja America/Argentina/Mendoza America/Argentina/Rio_Gallegos America/Argentina/Salta America/Argentina/San_Juan America/Argentina/San_Luis America/Argentina/Tucuman America/Argentina/Ushuaia America/Buenos_Aires America/Catamarca America/Cordoba America/Jujuy America/Mendoza",
  AT: "Europe/Vienna",
  AZ: "Asia/Baku",
  BA: "Europe/Sarajevo",
  BD: "Asia/Dhaka",
  BE: "Europe/Brussels",
  BF: "Africa/Ouagadougou",
  BG: "Europe/Sofia",
  BH: "Asia/Bahrain",
  BI: "Africa/Bujumbura",
  BN: "Asia/Brunei",
  BO: "America/La_Paz",
  BR: "America/Araguaina America/Bahia America/Belem America/Boa_Vista America/Campo_Grande America/Cuiaba America/Eirunepe America/Fortaleza America/Maceio America/Manaus America/Noronha America/Porto_Velho America/Recife America/Rio_Branco America/Santarem America/Sao_Paulo",
  BY: "Europe/Minsk",
  CA: "America/Atikokan America/Blanc-Sablon America/Cambridge_Bay America/Coral_Harbour America/Creston America/Dawson America/Dawson_Creek America/Edmonton America/Fort_Nelson America/Glace_Bay America/Goose_Bay America/Halifax America/Inuvik America/Iqaluit America/Moncton America/Rankin_Inlet America/Regina America/Resolute America/St_Johns America/Swift_Current America/Toronto America/Vancouver America/Whitehorse America/Winnipeg",
  CD: "Africa/Kinshasa Africa/Lubumbashi",
  CG: "Africa/Brazzaville",
  CH: "Europe/Zurich",
  CI: "Africa/Abidjan",
  CL: "America/Coyhaique America/Punta_Arenas America/Santiago Pacific/Easter",
  CM: "Africa/Douala",
  CN: "Asia/Shanghai Asia/Urumqi",
  CO: "America/Bogota",
  CR: "America/Costa_Rica",
  CU: "America/Havana",
  CY: "Asia/Famagusta Asia/Nicosia",
  CZ: "Europe/Prague",
  DE: "Europe/Berlin Europe/Busingen",
  DJ: "Africa/Djibouti",
  DO: "America/Santo_Domingo",
  DZ: "Africa/Algiers",
  EC: "America/Guayaquil Pacific/Galapagos",
  EG: "Africa/Cairo",
  ER: "Africa/Asmara Africa/Asmera",
  ES: "Africa/Ceuta Atlantic/Canary Europe/Madrid",
  ET: "Africa/Addis_Ababa",
  FI: "Europe/Helsinki",
  FR: "Europe/Paris",
  GH: "Africa/Accra",
  GM: "Africa/Banjul",
  GN: "Africa/Conakry",
  GR: "Europe/Athens",
  GT: "America/Guatemala",
  HK: "Asia/Hong_Kong",
  HN: "America/Tegucigalpa",
  HR: "Europe/Zagreb",
  ID: "Asia/Jakarta Asia/Jayapura Asia/Makassar Asia/Pontianak",
  IL: "Asia/Jerusalem",
  IN: "Asia/Calcutta Asia/Kolkata",
  IQ: "Asia/Baghdad",
  IR: "Asia/Tehran",
  IT: "Europe/Rome",
  JO: "Asia/Amman",
  JP: "Asia/Tokyo",
  KE: "Africa/Nairobi",
  KG: "Asia/Bishkek",
  KH: "Asia/Phnom_Penh",
  KM: "Indian/Comoro",
  KR: "Asia/Seoul",
  KW: "Asia/Kuwait",
  KZ: "Asia/Almaty Asia/Aqtau Asia/Aqtobe Asia/Atyrau Asia/Oral Asia/Qostanay Asia/Qyzylorda",
  LB: "Asia/Beirut",
  LK: "Asia/Colombo",
  LT: "Europe/Vilnius",
  LU: "Europe/Luxembourg",
  LY: "Africa/Tripoli",
  MA: "Africa/Casablanca",
  MD: "Europe/Chisinau",
  ME: "Europe/Podgorica",
  MG: "Indian/Antananarivo",
  MK: "Europe/Skopje",
  ML: "Africa/Bamako",
  MR: "Africa/Nouakchott",
  MT: "Europe/Malta",
  MV: "Indian/Maldives",
  MW: "Africa/Blantyre",
  MX: "America/Bahia_Banderas America/Cancun America/Chihuahua America/Ciudad_Juarez America/Hermosillo America/Matamoros America/Mazatlan America/Merida America/Mexico_City America/Monterrey America/Ojinaga America/Tijuana",
  MY: "Asia/Kuala_Lumpur Asia/Kuching",
  MZ: "Africa/Maputo",
  NE: "Africa/Niamey",
  NG: "Africa/Lagos",
  NI: "America/Managua",
  NL: "Europe/Amsterdam",
  NO: "Europe/Oslo",
  NP: "Asia/Kathmandu Asia/Katmandu",
  OM: "Asia/Muscat",
  PA: "America/Panama",
  PE: "America/Lima",
  PH: "Asia/Manila",
  PK: "Asia/Karachi",
  PL: "Europe/Warsaw",
  PR: "America/Puerto_Rico",
  PS: "Asia/Gaza Asia/Hebron",
  PT: "Atlantic/Azores Atlantic/Madeira Europe/Lisbon",
  PY: "America/Asuncion",
  QA: "Asia/Qatar",
  RO: "Europe/Bucharest",
  RS: "Europe/Belgrade",
  RU: "Asia/Anadyr Asia/Barnaul Asia/Chita Asia/Irkutsk Asia/Kamchatka Asia/Khandyga Asia/Krasnoyarsk Asia/Magadan Asia/Novokuznetsk Asia/Novosibirsk Asia/Omsk Asia/Sakhalin Asia/Srednekolymsk Asia/Tomsk Asia/Ust-Nera Asia/Vladivostok Asia/Yakutsk Asia/Yekaterinburg Europe/Astrakhan Europe/Kaliningrad Europe/Kirov Europe/Moscow Europe/Samara Europe/Saratov Europe/Ulyanovsk Europe/Volgograd",
  RW: "Africa/Kigali",
  SA: "Asia/Riyadh",
  SD: "Africa/Khartoum",
  SE: "Europe/Stockholm",
  SG: "Asia/Singapore",
  SN: "Africa/Dakar",
  SO: "Africa/Mogadishu",
  SV: "America/El_Salvador",
  SY: "Asia/Damascus",
  TD: "Africa/Ndjamena",
  TH: "Asia/Bangkok",
  TJ: "Asia/Dushanbe",
  TM: "Asia/Ashgabat",
  TN: "Africa/Tunis",
  TR: "Europe/Istanbul",
  TW: "Asia/Taipei",
  TZ: "Africa/Dar_es_Salaam",
  UA: "Europe/Kiev Europe/Kyiv Europe/Simferopol",
  UG: "Africa/Kampala",
  UY: "America/Montevideo",
  UZ: "Asia/Samarkand Asia/Tashkent",
  VE: "America/Caracas",
  VN: "Asia/Ho_Chi_Minh Asia/Saigon",
  VU: "Pacific/Efate",
  YE: "Asia/Aden",
  ZA: "Africa/Johannesburg",
  ZM: "Africa/Lusaka",
  ZW: "Africa/Harare",
});
