/**
 * Country (ISO 3166-1 alpha-2) → the catalogue languages most spoken there, most spoken first.
 * Only languages the translation catalogue carries are listed, and English-only countries are
 * left out entirely: English is already pinned near the top of the rail for everyone.
 *
 * This is ranking data for the translation rail, not a statement about any population — a wrong
 * guess only reorders the list, it never selects anything.
 */
export const REGION_LANGUAGES: Readonly<Record<string, readonly string[]>> = Object.freeze({
  // South and Central Asia
  PK: ["ur", "pa", "sd", "ps"],
  IN: ["hi", "bn", "ur", "te", "mr", "ta", "gu", "kn", "ml", "pa", "as", "ks"],
  BD: ["bn"],
  AF: ["ps", "prs", "fa", "uz", "tk"],
  IR: ["fa", "az", "ku", "tk"],
  LK: ["si", "ta"],
  MV: ["dv"],
  NP: ["ne"],
  UZ: ["uz", "tg", "ru"],
  TJ: ["tg", "uz", "ru"],
  KZ: ["kk", "ru"],
  KG: ["ky", "uz", "ru"],
  TM: ["tk", "ru"],
  AZ: ["az"],
  // East and South-East Asia
  ID: ["id"],
  MY: ["ms", "zh", "ta"],
  BN: ["ms"],
  SG: ["ms", "zh", "ta"],
  PH: ["fil", "tl", "ceb", "mdh", "mrw"],
  TH: ["th", "ms"],
  VN: ["vi"],
  KH: ["km"],
  CN: ["zh", "ug"],
  TW: ["zh"],
  HK: ["zh"],
  JP: ["ja"],
  KR: ["ko"],
  // Middle East and North Africa
  SA: ["ar"],
  AE: ["ar", "ur", "hi"],
  QA: ["ar", "ur"],
  KW: ["ar"],
  BH: ["ar"],
  OM: ["ar"],
  YE: ["ar"],
  IQ: ["ar", "ku"],
  SY: ["ar", "ku"],
  JO: ["ar"],
  LB: ["ar", "fr"],
  PS: ["ar"],
  IL: ["he", "ar"],
  EG: ["ar"],
  LY: ["ar"],
  TN: ["ar", "fr"],
  DZ: ["ar", "zgh", "ber", "fr"],
  MA: ["ar", "zgh", "ber", "fr"],
  MR: ["ar", "ff", "fr"],
  SD: ["ar"],
  TR: ["tr", "ku"],
  CY: ["el", "tr"],
  // Europe
  AL: ["sq"],
  BA: ["bs", "hr", "sr"],
  RS: ["sr"],
  ME: ["sr", "sq"],
  HR: ["hr"],
  MK: ["mk", "sq"],
  BG: ["bg", "tr"],
  RO: ["ro"],
  MD: ["ro", "ru"],
  GR: ["el"],
  MT: ["mt"],
  IT: ["it"],
  FR: ["fr"],
  BE: ["nl", "fr", "de"],
  NL: ["nl"],
  LU: ["fr", "de"],
  CH: ["de", "fr", "it"],
  DE: ["de", "tr"],
  AT: ["de"],
  ES: ["es"],
  PT: ["pt"],
  PL: ["pl"],
  CZ: ["cs"],
  LT: ["lt"],
  SE: ["sv"],
  NO: ["no"],
  FI: ["fi", "sv"],
  RU: ["ru", "tt"],
  UA: ["uk", "ru"],
  BY: ["be", "ru"],
  // The Americas
  CA: ["fr"],
  BR: ["pt"],
  MX: ["es"],
  AR: ["es"],
  CO: ["es"],
  CL: ["es"],
  PE: ["es"],
  VE: ["es"],
  EC: ["es"],
  GT: ["es"],
  CU: ["es"],
  BO: ["es"],
  DO: ["es"],
  HN: ["es"],
  PY: ["es"],
  SV: ["es"],
  NI: ["es"],
  CR: ["es"],
  PA: ["es"],
  UY: ["es"],
  PR: ["es"],
  // Sub-Saharan Africa
  SO: ["so", "ar"],
  DJ: ["so", "aa", "fr", "ar"],
  ET: ["am", "om", "so", "aa"],
  ER: ["aa", "ar"],
  KE: ["sw", "luy", "so"],
  TZ: ["sw"],
  UG: ["lg", "sw"],
  RW: ["rw", "fr"],
  BI: ["rn", "fr"],
  CD: ["ln", "sw", "fr"],
  CG: ["ln", "fr"],
  NG: ["ha", "yo", "ff"],
  NE: ["ha", "ff", "fr"],
  GH: ["ak", "tw", "dag", "ha"],
  CM: ["ff", "fr", "ha"],
  SN: ["ff", "fr"],
  ML: ["bm", "ff", "fr"],
  BF: ["mos", "ff", "fr"],
  GN: ["ff", "nqo", "fr"],
  CI: ["fr", "bm"],
  TD: ["ar", "fr"],
  GM: ["ff"],
  MW: ["ny", "yao"],
  MZ: ["pt", "yao", "ny"],
  ZM: ["ny"],
  ZW: ["sn"],
  ZA: ["zu"],
  MG: ["mg", "fr"],
  KM: ["ar", "fr"],
  VU: ["bi", "fr"],
});
